server:
  max-http-header-size: 10240
  tomcat:
    accesslog:
      directory: /data/logs/oauth_server/historyRunLog/access
      enabled: true
      pattern: common
      prefix: auth-server-access
      suffix: .log
      rotate: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: happy-mix-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: o7r2FkapLfHzbQ==
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 300
      # 连接池中的最小空闲连接
      min-idle: 200
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@happy-mix-discovery-eureka:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 30    #设置心跳时长
hystrix:
  threadpool:
    default:
      coreSize: 1000
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          strategy: SEMAPHORE
          thread:
            #目前有两个容器实例，单个请求超时5s,+重试>10s，超15s则熔断
            timeoutInMilliseconds: 30000
ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  #ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 5000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout,超时时间不可大于断路器的超时时间
  ReadTimeout: 5000
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 5000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#微信小程序相关信息
weixin:
  member:
    appid: wx6a9ed7e30ba12e49
    secret: d0f5bbbde4d1f993645b0a6746fb17c8
    # 周美玲本地调试
#    appid: wx3d27cc3626b44fc9
#    secret: 7e880299b445852799b4d0377dec0a18
logging:
  level:
    org.springframework: info
    cn.lfn.happy.mix.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}.yml
