server:
  max-http-header-size: 10240
  tomcat:
    accesslog:
      directory: /data/logs/circle_mall/historyRunLog/access
      enabled: true
      pattern: common
      prefix: circle-mall-access
      suffix: .log
      rotate: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 30    #设置心跳时长
hystrix:
  threadpool:
    default:
      coreSize: 1000
  command:
    default:
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: 3000
  ReadTimeout: 5000
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 5000
feign:
  hystrix:
    enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  rocketmq:
    stock:
      consumer:
        namesrv-addr: localhost:9876
        group-name: ticket-consumer
        topic: ticket
        check-keys: check
        consume-failure-retry-times: 3
      producer:
        namesrv-addr: localhost:9876
        group-name: ticket-check-producer
        topic: ticket-check
      producer2:
        namesrv-addr: localhost:9876
        group-name: good-stock-producer
        topic: stock
        check-keys: check
        confirm-message-faiure-retry-times: 3
      consumer2:
        namesrv-addr: localhost:9876
        group-name: good-stock-check-consumer
        topic: stock-check
        consume-failure-retry-times: 3
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: o7r2FkapLfHzbQ==
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 300
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 50
  datasource:
    name: dev
    url: jdbc:mysql://localhost:8635/hm-circle-mall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: happy
    password: HM4W+Shgin32v2mufO0N2cPZx7A=
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionInitSqls: set names utf8mb4    
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 300
    initialSize: 10
    maxWait: 60000
    minIdle: 50
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 200
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lfn.happy.mix.entity
logging:
  level:
    org.springframework: info
    cn.lfn.happy.mix.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}.yml
