server:
  max-http-header-size: 10240
  tomcat:
    accesslog:
      directory: /data/logs/member/historyRunLog/access
      enabled: true
      pattern: common
      prefix: member-access
      suffix: .log
      rotate: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rocketmq:
    member:
      producer:
        namesrv-addr: localhost:9876
        group-name: member-producer
        topic: member
        check-keys: check
        confirm-message-faiure-retry-times: 3
      consumer:
        namesrv-addr: localhost:9876
        group-name: point-order-consumer
        topic: member-check
        consume-failure-retry-times: 3
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  datasource:
    name: dev
    url: jdbc:mysql://172.18.202.153:8635/hm-member?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: happy
    password: happy-mix
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lfn.happy.mix.entity
systemconstant:
  memberUrl:
    sendMsg: http://TOOLS/tools/sms/send2phonewithoutmessageCount
  weixinConstants:
    mpAppId: wx6a9ed7e30ba12e49
    mchKey: gainhonve7D4YMGwBUTqi1Qe8G1831a8
    mchId: 1509776891
    keyPath: /data/happy/wechat_cert/apiclient_cert.pem
    notifyUrl: http://localhost:60003/account/point/notifyPointRecharge.do
    sandboxNotifyUrl: http://huwei.zhubaogongyuan.net:888/pc-circle/account/point/notifyPointRecharge.do
    useSandbox: true
    ip: 192.168.40.136
point: 1
logging:
  level:
    org.springframework: info
    cn.lfn.happy.mix.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}1.yml