spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
server:
  tomcat:
    accesslog:
      directory: /data/logs/pc_system_web/historyRunLog/access
      enabled: true
      pattern: common
      prefix: pc-system-web-access
      suffix: .log
      rotate: true
hystrix:
  threadpool:
    default:
      coreSize: 1000
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          strategy: SEMAPHORE
          thread:
            #目前有两个容器实例，单个请求超时5s,+重试>10s，超15s则熔断
            timeoutInMilliseconds: 30000
ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  #ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 5000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout,超时时间不可大于断路器的超时时间
  ReadTimeout: 10000
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 5000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@happy-mix-discovery-eureka:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 30    #设置心跳时长
# 认证地址 zuul地址转发
auth-server: https://www.zberp.fun/auth-server
security:
  oauth2:
    client:
      client-id: CLIENT_SYSTEM_PLATFORM
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
    resource:
      id: oauth2_resouce_system_pc
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
logging:
  level:
    org.springframework: info
    cn.lfn.happy.mix.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}.yml
