spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  tomcat:
    accesslog:
      directory: /data/logs/pc_system_web/historyRunLog/access
      enabled: true
      pattern: common
      prefix: pc-system-web-access
      suffix: .log
      rotate: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 30    #设置心跳时长
# 认证地址 zuul地址转发
auth-server: http://127.0.0.1:60003/auth-server
security:
  oauth2:
    client:
      client-id: CLIENT_SYSTEM_PLATFORM
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
    resource:
      id: oauth2_resouce_system_pc
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
logging:
  level:
    org.springframework: info
    cn.lfn.happy.mix.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}.yml
