zuul:
  ratelimit:
    #启用限流策略
    enabled: true
    #配置RateLimiter数据存储方式为redis，防止集群时 ConcurrentHashMap 不统一
    repository: redis
    default-policy:
      #每个ip 1秒内访问次数不得超过3次且总计访问时间这不得超过18秒
      limit: 3
      quota: 30
      refresh-interval: 1
      type: origin
    policies:
      #指定某个服务单独配置限流，与默认限流配置互不影响
      #每个Url1秒内访问次数不得超过10次且总计访问时间这不得超过600秒
      wechat-member:
        limit: 100
        quota: 600
        refresh-interval: 1
        type: url
  eager-load:
    enabled: true
  semaphore:
    max-semaphores: 2000
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
    maxTotalConnections: 2000
    maxPerRouteConnections: 2000
  ignored-services: '*'
  routes:
    wechat-member:
      path: /wechat-member/**
      sensitiveHeaders:
      serviceId: wechat-member-web
    wechat-assistant:
      path: /wechat-assistant/**
      sensitiveHeaders:
      serviceId: wechat-assistant-web
    pc-system:
      path: /pc-system/**
      sensitiveHeaders:
      serviceId: pc-system-web
    pc-circle:
      path: /pc-circle/**
      sensitiveHeaders:
      serviceId: pc-circle-web
#    integral-mall:
#      path: /integral-mall/**
#      sensitiveHeaders:
#      serviceId: integral-mall
    auth-server:
      path: /auth-server/**
      sensitiveHeaders:
      serviceId: auth-server
#    pc-circle-web-dev:
#      path: /pc-circle-web-dev/**
#      sensitiveHeaders:
#      serviceId: pc-circle-web-dev
  add-proxy-headers: true
hystrix:
  threadpool:
    default:
      coreSize: 1000
  command:
    default:
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          strategy: SEMAPHORE
          thread:
            #目前有两个容器实例，单个请求超时5s,+重试>10s，超15s则熔断
            timeoutInMilliseconds: 15000
ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  #ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 3000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout,超时时间不可大于断路器的超时时间
  ReadTimeout: 10000
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 5000
feign:
  hystrix:
    enabled: true
spring:
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: 192.168.40.70
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12345678
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0